CREATE TABLE FootballMatch(
Id Number,
"Value" BLOB,
CONSTRAINT PK_FootballMatch PRIMARY KEY (Id)
);

CREATE SEQUENCE SQ_FootballMatch_Id
	MINVALUE 1
	START WITH 1
	INCREMENT BY 1
	CACHE 10;

SELECT * FROM FootballMatch;
